version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: student
      POSTGRES_USER: student
      POSTGRES_DATABASE: student
    ports:
      - "5432:5432"